hhenergy <- read.table("householdpc.txt", header=TRUE, sep=";", dec =";")
hhenergy2 <- read.table("householdpc.txt", header=TRUE, sep=";", na.strings = "?", nrows= 2075259, stringsAsFactors=FALSE)
hhenergy2$DateTime <- paste(hhenergy2$Date, hhenergy2$Time)
hhenergy2$DateTime <- as.Date(hhenergy2$DateTime, format = "%d/%m/%Y %H: %M: %S")
View(hhenergy2)
library(dplyr)
subset_hhe <- filter(hhenergy2, DateTime >= as.Date("2007-02-01 00:00:00"), DateTime < as.Date ("2007-02-02 00:00:00"))
subset_hhe$Date <- as.Date(subset_hhe$Date, format="%d/%m/%Y")
subset_hhe$Time <- strptime(subset_hhe$Time, format="%H:%M:%S")
subset_hhe[1:1440,"Time"] <- format(subset_hhe[1:1440,"Time"],"2007-02-01 %H:%M:%S")
subset_hhe[1441:2880,"Time"] <- format(subset_hhe[1441:2880,"Time"],"2007-02-02 %H:%M:%S")
plot(subset_hhe$Time,as.numeric(as.character(subset_hhe$Global_active_power)),type="l",xlab="",ylab="Global Active Power (kilowatts)")
title(main="Global Active Power Vs Time")
png("plot2.png", width=480, height=480)