hhenergy <- read.table("householdpc.txt", header=TRUE, sep=";", dec =";")
hhenergy2 <- read.table("householdpc.txt", header=TRUE, sep=";", na.strings = "?", nrows= 2075259, stringsAsFactors=FALSE)
hhenergy2$DateTime <- paste(hhenergy2$Date, hhenergy2$Time)
hhenergy2$DateTime <- as.Date(hhenergy2$DateTime, format = "%d/%m/%Y %H: %M: %S")
View(hhenergy2)
library(dplyr)
subset_hhe <- filter(hhenergy2, DateTime >= as.Date("2007-02-01 00:00:00"), DateTime < as.Date ("2007-02-02 00:00:00"))
subset_hhe$Date <- as.Date(subset_hhe$Date, format="%d/%m/%Y")
subset_hhe$Time <- strptime(subset_hhe$Time, format="%H:%M:%S")
subset_hhe[1:1440,"Time"] <- format(subset_hhe[1:1440,"Time"],"2007-02-01 %H:%M:%S")
subset_hhe[1441:2880,"Time"] <- format(subset_hhe[1441:2880,"Time"],"2007-02-02 %H:%M:%S")
par(mfrow=c(1,4))
with(subset_hhe,{
  plot(subset_hhe$Time,as.numeric(as.character(subset_hhe$Global_active_power)),type="l",  xlab="",ylab="Global Active Power")  
  plot(subset_hhe$Time,as.numeric(as.character(subset_hhe$Voltage)), type="l",xlab="datetime",ylab="Voltage")
  plot(subset_hhe$Time,subset_hhe$Sub_metering_1,type="n",xlab="",ylab="Energy sub metering")
  with(subset_hhe,lines(Time,as.numeric(as.character(Sub_metering_1))))
  with(subset_hhe,lines(Time,as.numeric(as.character(Sub_metering_2)),col="red"))
  with(subset_hhe,lines(Time,as.numeric(as.character(Sub_metering_3)),col="blue"))
  legend("topright", lty=1, col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), cex = 0.6)
  plot(subset_hhe$Time,as.numeric(as.character(subset_hhe$Global_reactive_power)),type="l",xlab="datetime",ylab="Global_reactive_power")
  })
title(main="Energy sub-metering")
png("plot4.png", width=480, height=480)